name: Publish Docker

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 5

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Build
        working_directory: ./PWABuilder.IOS.Cli
        run: |
          dotnet publish -c Release -o ./bin/publish
          rm ./bin/publish/*.pdb
          rm ./bin/publish/*.dbg

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker
        uses: docker/build-push-action@v3
        with:
          context: ./PWABuilder.IOS.Cli
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ios-pwa-builder:latest
